/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DocumentManager.java
 *
 * Created on 2011-01-25, 15:13:13
 */

package invenio.pdf.trainingset;

import java.awt.Graphics2D;
import java.awt.Rectangle;

/**
 *
 * @author piotr
 */
public class DocumentManager extends javax.swing.JFrame {

    /** Creates new form DocumentManager */
    public DocumentManager() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filePanel = new javax.swing.JPanel();
        fileNameLabel = new javax.swing.JLabel();
        openFileButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pagePlotPanel = new javax.swing.JPanel();
        nextPageBtn = new javax.swing.JButton();
        pageSelect = new javax.swing.JComboBox();
        prevPlotBtn = new javax.swing.JButton();
        newPlotBtn = new javax.swing.JButton();
        nextPlotBtn = new javax.swing.JButton();
        plotSelect = new javax.swing.JComboBox();
        prevPageBtn = new javax.swing.JButton();
        deletePlotBtn = new javax.swing.JButton();
        contentPanel = new javax.swing.JSplitPane();
        plotControlsPanel = new javax.swing.JPanel();
        plotPositionPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        plotPositionLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pltCaptionPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        captionTextArea = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        pageContentPanel = new javax.swing.JScrollPane();
        plotsDrawingArea1 = new invenio.pdf.trainingset.PlotsDrawingArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("documentManagerFrame"); // NOI18N

        filePanel.setName("filePanel"); // NOI18N

        fileNameLabel.setText("name of the file currently open");
        fileNameLabel.setName("filePathLabel"); // NOI18N

        openFileButton.setText("Open...");
        openFileButton.setName("openFileButton"); // NOI18N
        openFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Open file:");

        javax.swing.GroupLayout filePanelLayout = new javax.swing.GroupLayout(filePanel);
        filePanel.setLayout(filePanelLayout);
        filePanelLayout.setHorizontalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filePanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fileNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(openFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(540, Short.MAX_VALUE))
        );
        filePanelLayout.setVerticalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(fileNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(openFileButton))
        );

        pagePlotPanel.setName("pagesPanel"); // NOI18N

        nextPageBtn.setText("next page");
        nextPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPageBtnActionPerformed(evt);
            }
        });

        pageSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pageSelect.setName("pageSelect"); // NOI18N

        prevPlotBtn.setText("prev. plot");

        newPlotBtn.setText("new plot");

        nextPlotBtn.setText("next plot");

        plotSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        plotSelect.setName("plotSelect"); // NOI18N
        plotSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotSelectActionPerformed(evt);
            }
        });

        prevPageBtn.setText("prev. page");

        deletePlotBtn.setText("delete plot");

        javax.swing.GroupLayout pagePlotPanelLayout = new javax.swing.GroupLayout(pagePlotPanel);
        pagePlotPanel.setLayout(pagePlotPanelLayout);
        pagePlotPanelLayout.setHorizontalGroup(
            pagePlotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pagePlotPanelLayout.createSequentialGroup()
                .addComponent(prevPageBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pageSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextPageBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(prevPlotBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plotSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextPlotBtn)
                .addGap(18, 18, 18)
                .addComponent(deletePlotBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newPlotBtn))
        );
        pagePlotPanelLayout.setVerticalGroup(
            pagePlotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagePlotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(prevPageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pageSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addComponent(nextPageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(newPlotBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deletePlotBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nextPlotBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(plotSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
            .addComponent(prevPlotBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        nextPageBtn.getAccessibleContext().setAccessibleParent(pagePlotPanel);
        pageSelect.getAccessibleContext().setAccessibleParent(pagePlotPanel);
        prevPlotBtn.getAccessibleContext().setAccessibleParent(pagePlotPanel);
        newPlotBtn.getAccessibleContext().setAccessibleParent(pagePlotPanel);
        nextPlotBtn.getAccessibleContext().setAccessibleParent(pagePlotPanel);
        plotSelect.getAccessibleContext().setAccessibleParent(pagePlotPanel);
        prevPageBtn.getAccessibleContext().setAccessibleParent(pagePlotPanel);

        contentPanel.setDividerLocation(800);
        contentPanel.setResizeWeight(1.0);

        plotControlsPanel.setMaximumSize(new java.awt.Dimension(300, 32767));
        plotControlsPanel.setPreferredSize(new java.awt.Dimension(300, 702));

        jLabel1.setText("Plot position:");

        plotPositionLabel.setText("(here the plots position)");

        jButton1.setText("Select plot boundary");

        javax.swing.GroupLayout plotPositionPanelLayout = new javax.swing.GroupLayout(plotPositionPanel);
        plotPositionPanel.setLayout(plotPositionPanelLayout);
        plotPositionPanelLayout.setHorizontalGroup(
            plotPositionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plotPositionPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(plotPositionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );
        plotPositionPanelLayout.setVerticalGroup(
            plotPositionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plotPositionPanelLayout.createSequentialGroup()
                .addGroup(plotPositionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(plotPositionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        jLabel3.setText("Caption position:");

        jLabel4.setText("(here the position of a plot)");

        jLabel5.setText("Caption text:");

        captionTextArea.setColumns(20);
        captionTextArea.setRows(5);
        jScrollPane1.setViewportView(captionTextArea);

        jButton2.setText("Select caption");

        javax.swing.GroupLayout pltCaptionPanelLayout = new javax.swing.GroupLayout(pltCaptionPanel);
        pltCaptionPanel.setLayout(pltCaptionPanelLayout);
        pltCaptionPanelLayout.setHorizontalGroup(
            pltCaptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pltCaptionPanelLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
            .addGroup(pltCaptionPanelLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );
        pltCaptionPanelLayout.setVerticalGroup(
            pltCaptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pltCaptionPanelLayout.createSequentialGroup()
                .addGroup(pltCaptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pltCaptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        javax.swing.GroupLayout plotControlsPanelLayout = new javax.swing.GroupLayout(plotControlsPanel);
        plotControlsPanel.setLayout(plotControlsPanelLayout);
        plotControlsPanelLayout.setHorizontalGroup(
            plotControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plotPositionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pltCaptionPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        plotControlsPanelLayout.setVerticalGroup(
            plotControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plotControlsPanelLayout.createSequentialGroup()
                .addComponent(plotPositionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(pltCaptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
        );

        contentPanel.setRightComponent(plotControlsPanel);

        javax.swing.GroupLayout plotsDrawingArea1Layout = new javax.swing.GroupLayout(plotsDrawingArea1);
        plotsDrawingArea1.setLayout(plotsDrawingArea1Layout);
        plotsDrawingArea1Layout.setHorizontalGroup(
            plotsDrawingArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        plotsDrawingArea1Layout.setVerticalGroup(
            plotsDrawingArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );

        pageContentPanel.setViewportView(plotsDrawingArea1);

        contentPanel.setLeftComponent(pageContentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pagePlotPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1078, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(filePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pagePlotPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPageBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextPageBtnActionPerformed

    private void plotSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plotSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plotSelectActionPerformed

    private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileButtonActionPerformed
            // TODO add your handling code here:
        Graphics2D gc= (Graphics2D) pageContentPanel.getGraphics();
        gc.drawLine(0, 0, 800, 800);
        
    }//GEN-LAST:event_openFileButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DocumentManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea captionTextArea;
    private javax.swing.JSplitPane contentPanel;
    private javax.swing.JButton deletePlotBtn;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JPanel filePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newPlotBtn;
    private javax.swing.JButton nextPageBtn;
    private javax.swing.JButton nextPlotBtn;
    private javax.swing.JButton openFileButton;
    private javax.swing.JScrollPane pageContentPanel;
    private javax.swing.JPanel pagePlotPanel;
    private javax.swing.JComboBox pageSelect;
    private javax.swing.JPanel plotControlsPanel;
    private javax.swing.JLabel plotPositionLabel;
    private javax.swing.JPanel plotPositionPanel;
    private javax.swing.JComboBox plotSelect;
    private invenio.pdf.trainingset.PlotsDrawingArea plotsDrawingArea1;
    private javax.swing.JPanel pltCaptionPanel;
    private javax.swing.JButton prevPageBtn;
    private javax.swing.JButton prevPlotBtn;
    // End of variables declaration//GEN-END:variables

}
